#!/bin/bash
#
# Wrapper to decrypt all vault encrypted files
# Platform: Unix
#
# Author:   Dmitriy Ivanov
#

# Environment
ANSIBLE_HOME="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# Script
${ANSIBLE_HOME}/av rekey '.enc'
