---
# ------------------ Variables ------------------
[all:vars]
ansible_become=True
ansible_become_method=sudo
ansible_managed="Ansible - Modified on %d %B %Y, %H:%M:%S %z %Z by {uid}"
ansible_ssh_common_args="-o ControlMaster=auto -o ControlPath=~/.ssh/mux-%r@%h:%p -o ControlPersist=30m -o ForwardAgent=yes -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
ansible_ssh_pipelining=True
ansible_ssh_private_key_file="~/.ssh/ssh-key-aws"
gathering=smart
hash_behaviour=merge
host_key_checking=False
nocows=True
timeout=360

# --------------- Infrastructure ----------------
[base:children]
tag_OS_centos

[centos:vars]
ansible_user=centos

[base:children]
centos
