.TH  py.py "1" "June 2015" "Python Utils" "User Commands"
.SH NAME
py.py \- Python program to print Users and Groups formatted table to standard output
.SH SYNOPSIS
.B py.py
.SH DESCRIPTION
.\" Add any additional description here
.PP
Base64 print Users and Groups formatted table to standard output.
.PP
\fBMandatory arguments are not implemented.\fR
.SH AUTHOR
Written by \fIDmitry Ivanov\fR
